### ISSUE TITLE
Issue with rake task when setting up demo_mode in new Rails app. 

### ISSUE THREAD

**Issue by DanielRoende** [Betterment/demo_mode#4]
I'm trying to set up demo_mode in a new Rails app (tried with an older one as well, but same issue).

Running it on a Rails 7 app with Ruby 3.0.3.

What I'm getting is a failure with the rake task.

```
bundle exec rails generate demo_mode:install
      create  config/initializers/demo_mode.rb
      create  config/personas/sample_persona.rb
        rake  demo_mode:install:migrations
rake aborted!
Don't know how to build task 'demo_mode:install:migrations' (See the list of available tasks with `rake --tasks`)
```
And running it with --trace:

```
  rake  demo_mode:install:migrations --trace

rake aborted!
Don't know how to build task 'demo_mode:install:migrations' (See the list of available tasks with `rake --tasks`)
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/task_manager.rb:59:in `[]'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:159:in `invoke_task'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/home/daniel/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/daniel/.rbenv/versions/3.0.3/bin/rake:25:in `load'
/home/daniel/.rbenv/versions/3.0.3/bin/rake:25:in `<main>'
```

Thank you in advance! Demo_mode looks amazing!

**Comment by smudge** [comment]
Thanks for the report @DanielRoende! This should be fixed in the `1.0.3` release!
